### PR TITLE
Simplify install by inlining vega renderer

### PR DESCRIPTION
**Pull request by saulshanabrook**
This simplifies the installation by inling the new Vega 5 / Vega Lite 3 renderer added to JupyterLab.

Once JupyterLab 1.0 is released, we can remove this inlined renderer.

This also updated the binder build to work with the latest features. You should be able to try out this branch at https://mybinder.org/v2/gh/Quansight/jupyterlab-omnisci/simpler-install?urlpath=lab/tree/notebooks/ These two notebooks should work:

* `notebooks/Ibis + Altair + Extraction.ipynb`
* `notebooks/Vega Lite 3 Test.ipynb`

### CODE REVIEW

**Comment by ian-r-rose** [comment]
I think there is a plan to release another alpha of JupyterLab imminently. Will this become moot when that happens? If so, you still want to merge this?

**Comment by saulshanabrook** [comment]
> I think there is a plan to release another alpha of JupyterLab imminently. Will this become moot when that happens?

Yep!

>  If so, you still want to merge this?

No, I guess not. Once that new alpha comes out, maybe you could update your PR for it, then we could merge that in, then I could update this one against master (it has some other cleanup changes as well so that things works on binder again), then we could merge this one in?

**Comment by ian-r-rose** [comment]
Sure, whatever works for you @saulshanabrook

**Comment by saulshanabrook** [comment]
I updated this to work with the JL alpha.

Since there hasn't been an alpha release yet that includes the recent Vega I still have that inlined.

I am testing this now on binder. I would like to merge this, if it works on binder, so that I people can try out this repo easily.

**Comment by saulshanabrook** [comment]
I also had to disable the jupyter widges example, since I don't believe there has been a beta release their for their JL extension for the alpha.

**Comment by saulshanabrook** [comment]
OK it seems to work on Binder! Merging this in.

**Comment by gnestor** [comment]
Thanks for working on this @saulshanabrook! I had this on my to do list, too. Are there are any follow up items that we should or could do to simplify more? I assume that we're including the conda steps to get python 3.6? I could submit a PR to ipywidgets to upgrade it to work properly with jupyterlab 1.0. I'm running lab 1.0.0-alpha.3 locally and widgets are working but I'm getting comm open/register errors:

```
default.js:924 Exception opening new comm
(anonymous) @ default.js:924
rejected @ default.js:7

default.js:132 Error: Object 'jupyter.widget' not found in registry
    at default.js:1472
    at new Promise (<anonymous>)
    at Object.loadObject (default.js:1451)
    at DefaultKernel.<anonymous> (default.js:917)
    at Generator.next (<anonymous>)
    at default.js:9
    at new Promise (<anonymous>)
    at push.YC29.__awaiter (default.js:5)
    at DefaultKernel._handleCommOpen (default.js:909)
    at DefaultKernel.<anonymous> (default.js:1016)
```

**Comment by saulshanabrook** [comment]
> Are there are any follow up items that we should or could do to simplify more?

Once the new alpha comes out we can remove the Vega renderer we have in here.

>  I assume that we're including the conda steps to get python 3.6?

Oh, no I was just including them because I use conda for most things now. It should work fine with another Python distribution as well.

>  I could submit a PR to ipywidgets to upgrade it to work properly with jupyterlab 1.0. I'm running lab 1.0.0-alpha.3 locally and widgets are working but I'm getting comm open/register errors:

Yeah I haven't tested any of the widget stuff since I assumed it would be broken. That would be great!

**Pull request merged**
