### PR TITLE
Add examples of using extract transform

### PR DESCRIPTION
**Pull request by saulshanabrook**
This adds a new notebook that shows why we need extract transform.

It reproduces most of the examples from https://www.omnisci.com/docs/latest/6_vegaTutorials.html#getting-more-from-your-data-1 using Altair and client side rendering.

These work currently, but we can't show all the data, because it's too much for the backend to return at once.

However, we do show how by using the newly added `extractTransforms` function in vega lite, we can put all the aggregates, binning,  and filtering in one place in the vega lite schema.

This makes the case for mapping those field to Ibix queries, so that the filtering and aggregating happens on the backend instead of on the frontend.

The overall goal here is to cover the use cases of MapD's custom vega backend, by using altair and regular SQL queries. So that users don't have to learn a new syntax to plot their data with the mapd backend.

### CODE REVIEW

**Comment by saulshanabrook** [comment]
Currently, we monkey patch `altair.Chart.__init__` to be able to deal with ibis queries.

If we end up moving forward on this, I can work on adding what we need to altair core. Which would be a dispatch mechanism on the input type, so that it can deal with things that aren't dataframes.

**Comment by saulshanabrook** [comment]
New goal is getting these examples working: https://vega.github.io/vega-lite-transforms2sql/

Based off this code: https://github.com/vega/vega-lite-transforms2sql/blob/master/transforms2sql.ts

**Comment by saulshanabrook** [comment]
Depends on https://github.com/ibis-project/ibis/pull/1675

**Comment by saulshanabrook** [comment]
That PR is merged now. This is ready to merge.

**Comment by ian-r-rose** [comment]
Thanks!

**Pull request merged**
