### PR TITLE
Python package

### PR DESCRIPTION
**Pull request by ian-r-rose**
Some minor cleanup of the python side of things. I don't know what was wrong with my environment before, but having this installable as a module seems fine to me now. I've moved the example notebooks back into a `notebooks` directory.

### CODE REVIEW

**Comment by saulshanabrook** [comment]
Thank you for cleanup, especially tidying up the code I just wrote :)

I will try this locally just to verify that it works for me as well and then seems good to merge.

**Comment by ian-r-rose** [comment]
Thanks! I have some uncommitted changes that I'll push later today

**Comment by ian-r-rose** [comment]
Okay, ready for a spin.

**Comment by saulshanabrook** [comment]
Works for me besides a mapd DB timeout on the new notebooks

screen shot 2018-11-12 at 11 30 23 am

**Comment by ian-r-rose** [comment]
Thanks!

**Pull request merged**
