### PR TITLE
Updates for JupyterLab 1.0.

### PR DESCRIPTION
**Pull request by ian-r-rose**
Updates for the JupyterLab prerelease.

### CODE REVIEW

**Comment by saulshanabrook** [comment]
Is it OK to hold off merging this till 1.0 is out?

I want it to still be possible to release new versions here and have them used without users having to clone JupyterLab master. If we can do that with the pre 1.0 release, then we can by all means merge this in.

**Comment by ian-r-rose** [comment]
Yep, no problem holding off.

Can you elaborate on what you mean about cutting a release? This PR should be compatible with the prerelease, so something like
```
pip install --pre jupyterlab
jupyter labextension install jupyterlab-omnisci@next
```
should work.

**Comment by saulshanabrook** [comment]
Ah yeah!

I spaced that we there was a prelease Python package, not only prelease JS packages.

Then I am fine merging this in before the official release.

**Comment by ian-r-rose** [comment]
Will this have to be updated for the `alpha.4. packages? I am not sure how the `npm` module version resolution works in this case.

**Comment by saulshanabrook** [comment]
@ian-r-rose I am not sure...

**Comment by saulshanabrook** [comment]
Who knows... I'll merge this for now, and we can always update again.

**Pull request merged**
