### PR TITLE
Jlab alpha 3

### PR DESCRIPTION
**Pull request by ian-r-rose**
@saulshanabrook Can you check whether your vega-5 stuff works with this and the new JupyterLab prerelease?

### CODE REVIEW

**Comment by saulshanabrook** [comment]
@ian-r-rose Sure, trying it now... https://mybinder.org/v2/gh/Quansight/jupyterlab-omnisci/jlab-alpha-2?urlpath=lab/tree/notebooks/4.%20Extract%20Use%20Cases%20-%20VL%20examples.ipynb

**Comment by ian-r-rose** [comment]
This will need to be updated again -- we had another round of package releases.

**Comment by ian-r-rose** [comment]
Okay, should be ready for a look.

**Comment by saulshanabrook** [comment]
OK it looks like it isn't rendering the Vega Lite. I will take a look into this.

**Comment by saulshanabrook** [comment]
> OK it looks like it isn't rendering the Vega Lite. I will take a look into this.

I bumped the version of JL installed in binder, that should fix this.

**Comment by saulshanabrook** [comment]
OK now it works. Thanks for this!

**Pull request merged**
