### PR TITLE
Session ID

### PR DESCRIPTION
**Pull request by ian-r-rose**
This teaches JupyterLab-OmniSci about session IDs, which will be necessary for the handoff between Immerse and JupyterLab. For the most part there are no user-facing changes, but components may be authenticated using a session ID instead of a username and password.

Likely there will be some cleanup required, but I kind of wanted to get this in soon-ish.

### CODE REVIEW

**Comment by ian-r-rose** [comment]
Actually, we shouldn't merge this yet -- it depends on unpublished versions of mapd-connector and ibis.

**Comment by ian-r-rose** [comment]
Okay, there have now been releases to `mapd-connector`, `ibis`, and `pymapd`, so this should be ready for review.

**Comment by ian-r-rose** [comment]
Updated for 1.0a8

**Comment by saulshanabrook** [comment]
@ian-r-rose to test this locally did you use docker to run a omnisi server or did you use a public one?

**Comment by ian-r-rose** [comment]
@saulshanabrook I tried it with both.

Here is a test script I used:
```python
import json

import pymapd

protocol = "https"
host = "metis.mapd.com"
port = 443

con = pymapd.connect(
    protocol=protocol,
    host=host,
    port=port,
    user="mapd",
    dbname="mapd",
    password="HyperInteractive",
)

with open("omnisci_session.json", "w") as f:
    f.write(json.dumps({
        "session": con._session,
        "query": "SELECT dest_lat, dest_lon FROM flights_donotmodify"
    }))
```

**Pull request merged**
