### PR TITLE
Support all of vega lite's view composition

### PR DESCRIPTION
**Pull request by saulshanabrook**
Vega lite supports a number of ways to compose multiple plots: https://vega.github.io/vega-lite/docs/composition.html

This PR adds support for all of them. Internally, this required supporting multiple data sets inside of one spec, and not assuming a global ibis expression.

I have also added an example of combining multiple different charts with different datasets to show off this feature:

screen shot 2019-02-04 at 12 23 08 pm

It is added in the existing example notebook.

### CODE REVIEW

**Comment by ian-r-rose** [comment]
@saulshanabrook Do I need to update my version of altair or ibis to specific branches? I am getting a lot of errors on the console and some empty charts (though some seem to render fine). Representative sample:

```javascript
ERROR Loading failed altair-data-7e38a97db9875f6cad301fe98ecd1127.json 404Not Found logger.js:3
The compiled spec uses Vega v3, but current version is 4.4.0.
embed.js:137
Exception opening new comm default.js:924
Error: "Object 'extract-vega-lite' not found in registry"
	loadObject http://localhost:8888/lab/static/vendors~main.15d5cb2fb48c4f259473.js:125337:28
	loadObject http://localhost:8888/lab/static/vendors~main.15d5cb2fb48c4f259473.js:125316:16
	_handleCommOpen http://localhost:8888/lab/static/vendors~main.15d5cb2fb48c4f259473.js:124782:36
	__awaiter http://localhost:8888/lab/static/vendors~main.15d5cb2fb48c4f259473.js:123874:71
	__awaiter http://localhost:8888/lab/static/vendors~main.15d5cb2fb48c4f259473.js:123870:12
	_handleCommOpen http://localhost:8888/lab/static/vendors~main.15d5cb2fb48c4f259473.js:124774:16
	_handleMessage http://localhost:8888/lab/static/vendors~main.15d5cb2fb48c4f259473.js:124881:31
	fulfilled http://localhost:8888/lab/static/vendors~main.15d5cb2fb48c4f259473.js:123871:48
default.js:132
Error: Invalid spec
```

**Comment by saulshanabrook** [comment]
@ian-r-rose Yeah I am running under the pre-released version of altair and vega lite: https://github.com/Quansight/jupyterlab-omnisci#bleed-edge-installation.

As a side note, I could make the install less horrible by copying jupyterlab's vega mimerenderer and using that, instead of depending on the core one. Then the installer wouldn't have to manually muck with their resolutions.

**Comment by saulshanabrook** [comment]
@ian-r-rose Can you verify the `resolutions` is correct in the staging package json?

You should be running with vega v4 which is pulled in when we bumpy the vega embed version.

**Comment by ian-r-rose** [comment]
I don't see any `resolutions` field in the `staging` `package.json`

**Comment by saulshanabrook** [comment]
@ian-r-rose Can you add one like it has in the README?

**Comment by ian-r-rose** [comment]
Oops, sorry :)

**Comment by ian-r-rose** [comment]
Hmm, the `jupyter lab build` step seems to be blowing away the `resolutions` field.

**Comment by saulshanabrook** [comment]
@ian-r-rose Yeah the resolutions has to go in the jupyter lab python package, not in the jupyter lab directory. This should give you the right file:

```bash
echo $(python -c 'import os; import jupyterlab; print(os.path.dirname(jupyterlab.__file__))')/staging/package.json
```

**Comment by ian-r-rose** [comment]
Now the charts are mostly working, thanks for the hand-holding @saulshanabrook! I am seeing some new errors on the console, are they important?
```
ERROR Error: "invalid format: %b"
	FormatSpecifier@http://localhost:8888/lab/static/vendors~ jupyter-widgets/controls~vega.3dd933b62461edbc58d8.js:101:44
	formatSpecifier@http://localhost:8888/lab/static/vendors~ jupyter-widgets/controls~vega.3dd933b62461edbc58d8.js:95:10
	newFormat@http://localhost:8888/lab/static/vendors~ jupyter-widgets/controls~vega.3dd933b62461edbc58d8.js:386:17
	tickFormat http://localhost:8888/lab/static/vendors~vega.4733253adf30c36c1a07.js:31190:19
	transform http://localhost:8888/lab/static/vendors~vega.4733253adf30c36c1a07.js:47067:28
	evaluate http://localhost:8888/lab/static/vendors~vega.4733253adf30c36c1a07.js:900:13
	run http://localhost:8888/lab/static/vendors~vega.4733253adf30c36c1a07.js:881:10
	run http://localhost:8888/lab/static/vendors~vega.4733253adf30c36c1a07.js:32366:14
	run http://localhost:8888/lab/static/vendors~vega.4733253adf30c36c1a07.js:26749:3
	done http://localhost:8888/lab/static/vendors~vega.4733253adf30c36c1a07.js:8486:11
	invokeCallback http://localhost:8888/lab/static/vendors~vega.4733253adf30c36c1a07.js:32416:9
	runAfter http://localhost:8888/lab/static/vendors~vega.4733253adf30c36c1a07.js:32455:5
	done http://localhost:8888/lab/static/vendors~vega.4733253adf30c36c1a07.js:8483:7
	request http://localhost:8888/lab/static/vendors~vega.4733253adf30c36c1a07.js:8538:7
logger.js:3
ERROR TypeError: "scene is undefined"
	draw http://localhost:8888/lab/static/vendors~vega.4733253adf30c36c1a07.js:46110:7
	draw http://localhost:8888/lab/static/vendors~vega.4733253adf30c36c1a07.js:38966:7
	visit http://localhost:8888/lab/static/vendors~vega.4733253adf30c36c1a07.js:27963:5
	draw http://localhost:8888/lab/static/vendors~vega.4733253adf30c36c1a07.js:38965:5
	visit http://localhost:8888/lab/static/vendors~vega.4733253adf30c36c1a07.js:27963:5
	draw http://localhost:8888/lab/static/vendors~vega.4733253adf30c36c1a07.js:38931:3
	draw http://localhost:8888/lab/static/vendors~vega.4733253adf30c36c1a07.js:46112:3
	draw http://localhost:8888/lab/static/vendors~vega.4733253adf30c36c1a07.js:38966:7
	visit http://localhost:8888/lab/static/vendors~vega.4733253adf30c36c1a07.js:27963:5
	draw http://localhost:8888/lab/static/vendors~vega.4733253adf30c36c1a07.js:38965:5
	visit http://localhost:8888/lab/static/vendors~vega.4733253adf30c36c1a07.js:27963:5
	draw http://localhost:8888/lab/static/vendors~vega.4733253adf30c36c1a07.js:38931:3
	draw http://localhost:8888/lab/static/vendors~vega.4733253adf30c36c1a07.js:46112:3
	_render http://localhost:8888/lab/static/vendors~vega.4733253adf30c36c1a07.js:46100:3
	_call http://localhost:8888/lab/static/vendors~vega.4733253adf30c36c1a07.js:19186:26
	render http://localhost:8888/lab/static/vendors~vega.4733253adf30c36c1a07.js:19189:3
	render http://localhost:8888/lab/static/vendors~vega.4733253adf30c36c1a07.js:26772:5
	run http://localhost:8888/lab/static/vendors~vega.4733253adf30c36c1a07.js:26757:7
	done http://localhost:8888/lab/static/vendors~vega.4733253adf30c36c1a07.js:8486:11
	invokeCallback http://localhost:8888/lab/static/vendors~vega.4733253adf30c36c1a07.js:32416:9
	runAfter http://localhost:8888/lab/static/vendors~vega.4733253adf30c36c1a07.js:32455:5
	done http://localhost:8888/lab/static/vendors~vega.4733253adf30c36c1a07.js:8483:7
```

**Comment by ian-r-rose** [comment]
Ah, okay. Sorry for misunderstanding.

This is a difficult bleeding-edge install, I do think it's a good idea to just copy the JupyterLab vega4 mimerenderer for now. Would it be possible to add a resolution to this `package.json`, then just import and re-export the extension so we don't duplicate code?

**Comment by saulshanabrook** [comment]
@ian-r-rose That's a weird one, haha haven't seen it. 

Sure I will work on copying/reusing the package so it's easier to install.

**Comment by ian-r-rose** [comment]
Do you think importing and re-exporting the `vega4-extension` would work?

**Comment by ian-r-rose** [comment]
I think this is good, we can work on improving the install story in a follow-up. Is there a reason to not update vega-embed in core JupyterLab?

**Comment by saulshanabrook** [comment]
>  Is there a reason to not update vega-embed in core JupyterLab?

Vega lite hasn't released v3 yet (it is on rc12) and so altair hasn't released support for it either. The latest vega embed depends on the prerelease version.

We could add support for it in core though, and just make it optional and lazy load.

**Pull request merged**
